### ISSUE TITLE
sandbox  sorunsalı

### ISSUE THREAD

**Issue by bferturk** [PisiLinuxNew/gonullu#21]
Depodaki paketlerin tamamı sandbox kullanılmadan derlenmiş durumda.Tekrar derleneceğinde sandbox açılmalı ancak sandbox hatası veren paketler için bir çözüm bulunmalı
Bu paketler : 
glibc ,dejavu-fonts ve virtualbox dur.

https://github.com/Pardus-Linux/buildfarm/blob/master/data/buildfarm.conf

dosyasında 42 numaralı satırda sandbox ile ilgi bir parametre verilmiş uygulayabilirsek iyi olur.

**Comment by MuhammetDilmac** [comment]
Develop brach'da sandbox kontrolü eklenmiş bulunmaktadır bu sebebiyet ile issue'yu kapatıyorum.
