### ISSUE TITLE
Firefox  Cpu %100 Ram %70 YAPTIKTAN SONRA DERLENDİ

### ISSUE THREAD

**Issue by Rmys** [PisiLinuxNew/gonullu#35]
Gonullu uygulamsı ile Firefox'u derlerken sürekili olarak ilk 900 sn de hızlı bir şekilde derleniyor. Sonra işlemci çalışması bir anda en alt seviyeye düşüyor, disk yazma 100-250 MB arasına çıkıyor ve Sistem izleyiciden baktığımda pisi hatalrı temizliyor şeklinde uyarı görüyor ve bu şekilde 3000-4000 saniyelere kadar devam ediyor en sonunda hata veriyordu. Birçok kez denedim aynı hatayı aldım. 
**Gonullu uygulaması ayarlarını CPU %100 Ram %70 şekinde değiştirdiğimde   derleme işlemi hatasız olarak gerçekleşti.**   Bilgilerinize

İşlemci İntel Xeon 4 Çekirdek 3,16 GHZ
Ram 4 GB

**Comment by MuhammetDilmac** [comment]
Verdiği hata neydi acaba?

**Comment by Rmys** [comment]
Başarısızların içerisindeki Firefoxları kaldırmışlar. Ekteki log dosyasını
kopyalamıştım sürekli buralarda derleme işlemi kesiliyordu.

2017-02-14 15:44 GMT+03:00 Muhammet Dilmaç <notifications@github.com>:

**Comment by Rmys** [comment]
İlk 900-950 sn de log dosyası 16000 satırı geçiyor. Bahsettiğim yavaşlama
sonrasında ancak 50-100 satır daha ekleniyordu. Derleme süresi 3000-4000
saniyelerdeyken hata veip hata dosyalarını sisteme gönderiyordu.

14 Şubat 2017 17:16 tarihinde Mustafa Cinasal <muscnsl@gmail.com> yazdı:

**Comment by MuhammetDilmac** [comment]
Hata dosyası olsaydı elimizde inceleyebilirdik :/ Lütfen benzer sorunun yaşanması durumunda hata dosyasını kenarda saklayınız.

Sorunun çözümlesi nedeni ile issue'yı kapatıyorum.

İlginiz için teşekkür ederiz. 
Diğer bildirimlerinizi bekliyoruz :)

**Comment by Rmys** [comment]
Tamam Teşekkürler


15 Şubat 2017 13:39 tarihinde Muhammet Dilmaç <notifications@github.com>
yazdı:
