### ISSUE TITLE
readme için

### ISSUE THREAD

**Issue by suvari** [PisiLinuxNew/gonullu#9]
sudo pisi it python3-setuptools
sudo pisi it python-devel
git clone https://github.com/PisiLinuxNew/gonullu
cd gonullu
sudo python3 setup.py install

olarak eklenmeli

**Comment by suvari** [comment]
çalıştırmak için;
gonullu
komutu yeterli, diye eklenmeli

**Comment by suvari** [comment]
sudo gonullu diye başlatılmalı

**Comment by MuhammetDilmac** [comment]
ilgili girdiler eklendi teşekkürler :)
